config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :categories

  resources :portfolios, except: [ :show ]
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  resources :blogs do
  	member do
  		get :toggle_status
  	end
  end

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  root to: 'pages#home'
end

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Would you like to work together?</h1>

<hr>

<div class="row">
  <div class="col-md-6">
    <h3>Office Address</h3>
    <p>16779 86 Ave, Surrey, BC</p>
    <h3>Phone</h3>
    <p><%= number_to_phone "5555555555" %></p>
    <h3>Email</h3>
    <p><a href="mailto:canvswang@hotmail.com?subject=PortfolioContact">Email me</a></p>
  </div>
  <div class="col-md-6">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2607.5769974464456!2d-122.85013708444353!3d49.189612879321295!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x5485d82ad672ef79%3A0x7b44815a5cbce013!2sSurrey%20Central%20Station!5e0!3m2!1sen!2sca!4v1585690335561!5m2!1sen!2sca" width="400" height="300" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
  </div>
</div>

app/views/pages/home.html.erb
<h1 class="cover-heading">Software Development is fun.</h1>
<p class="lead">Software development should NOT be a secret process, when I take on a new project, I make it my goal to not only deliver a well crafted product, but to also ensure that each stage of the process is fully communicated.</p>
<p class="lead">
  <%= link_to "Learn more", about_me_path, class: "btn btn-lg btn-secondary" %>
</p>